# DATA_FOLDER : /u01/Intern/chinhdv/DATA/milk/all_crop_data_origin
# train_csv : /u01/Intern/chinhdv/code/M_classification_torch/config/a/76classes_train_1103.csv
# val_csv: /u01/Intern/chinhdv/code/M_classification_torch/config/a/76classes_val_1103.csv
# TRAIN_FOLDER : /u01/DATA/HUMAN_ATTRIBUTE/PA_100K/data
TRAIN_FOLDER : /u01/chinhdv/code/human_attributes_omg/scripts/RAP_YOLO

train_csv : [

"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0000.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0001.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0002.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0003.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0004.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0005.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0006.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0007.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0008.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0009.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0010.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0011.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0012.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0013.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0014.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0015.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0016.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0017.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0018.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0019.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0020.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0021.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0022.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0023.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0024.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0025.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0026.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0027.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0028.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0029.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/escalator_task_0000.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v2_task_0001.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v2_task_0005.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v2_task_0009.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v2_task_0013.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v2_task_0068.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v2_task_0069.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v2_task_0070.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v2_task_0079.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_141_171_task_0000.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_141_171_task_0001.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_141_171_task_0002.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_141_171_task_0003.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_141_171_task_0004.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_141_171_task_0005.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_141_171_task_0006.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_141_171_task_0007.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_141_171_task_0008.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_141_171_task_0009.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_20_140_task_0000.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_20_140_task_0001.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_20_140_task_0002.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_20_140_task_0003.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_20_140_task_0004.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_20_140_task_0005.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_20_140_task_0006.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_20_140_task_0007.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_20_140_task_0008.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_20_140_task_0009.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_20_140_task_0010.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_20_140_task_0011.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_20_140_task_0012.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_20_140_task_0013.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_20_140_task_0014.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_20_140_task_0015.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_20_140_task_0016.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_20_140_task_0017.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_20_140_task_0018.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_20_140_task_0019.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_20_140_task_0020.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_23022022_task_0000.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_23022022_task_0001.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_23022022_task_0002.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_23022022_task_0003.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_23022022_task_0004.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_23022022_task_0005.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_23022022_task_0006.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_23022022_task_0007.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_23022022_task_0008.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_23022022_task_0009.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_entry_task_0000.csv",

]

val_csv : [
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0031.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0032.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0033.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0034.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0035.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_23022022_task_0012.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_23022022_task_0013.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_23022022_task_0014.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_entry_task_0001.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_23022022_task_0010.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_23022022_task_0011.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_141_171_task_0010.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_141_171_task_0011.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_20_140_task_0021.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_20_140_task_0022.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_20_140_task_0023.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_20_140_task_0024.csv",
]

test_csv : [
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_entry_task_0002.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_23022022_task_0015.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_23022022_task_0016.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v2_task_0080.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v2_task_0081.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v2_task_0082.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v2_task_0083.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v2_task_0084.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0036.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0037.csv",
#"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0038.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0039.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0040.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/body_part_detection_v1_task_0041.csv",
"/u01/chinhdv/code/human_attributes_omg/csv_RAP_YOLO/vin3s_2.csv",
]
classes:
    R_ub: ["None"]
    G_ub: ["None"]
    B_ub: ["None"]
    R_lb: ["None"]
    G_lb: ["None"]
    B_lb: ["None"]
  #  staff       : ["no", SalesAssistant, TechnicalStaff]

format_index: True

# task_weights : [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
task_weights : [1,1,1,1,1,1]
# task_weights : 1
class_weights:
    #age: [2,1,2]
    #    extract_age : [0,100]
    #gender: [1,1]
    # hair: [1,2]
    # hat         : [1, 1]
    # face_mask   : [1, 2]
    # glasses     : [1, 1]
    # visible     : [1,1]
    # body_pose   : [1, 1, 1]
    # backpack    : [1, 4]
    # handbag     : [1, 4]
    #ub_length   : [1, 1]
    #lb_length   : [1, 1]
    #    staff       : [1, 2, 2]
    # holding_object: [1, 4]
