# DATA_FOLDER : /u01/Intern/chinhdv/DATA/milk/all_crop_data_origin
# train_csv : /u01/Intern/chinhdv/code/M_classification_torch/config/a/76classes_train_1103.csv
# val_csv: /u01/Intern/chinhdv/code/M_classification_torch/config/a/76classes_val_1103.csv
# TRAIN_FOLDER : /u01/DATA/HUMAN_ATTRIBUTE/PA_100K/data
TRAIN_FOLDER : DATA_HUMAN_ATTRIBUTES/images

train_csv : [

]
# val_csv : [
#     # /u01/Intern/chinhdv/code/multi-task-classification/human_attribute_project/trainPA100K.csv,
#     /u01/Intern/chinhdv/code/multi-task-classification/human_attribute_project/0812_hmat_test.csv
# ]
test_csv : [
    ]

classes:
    R_ub: ['None']
    G_ub: ['None']
    B_ub: ['None']
    R_lb: ['None']
    G_lb: ['None']
    B_lb: ['None']
  #  staff       : ["no", SalesAssistant, TechnicalStaff]

format_index: True

# task_weights : [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
task_weights : [1,1,1,1,1]
# task_weights : 1
class_weights:
    #age: [2,1,2]
    #    extract_age : [0,100]
    #gender: [1,1]
    # hair: [1,2]
    # hat         : [1, 1]
    # face_mask   : [1, 2]
    # glasses     : [1, 1]
    # visible     : [1,1]
    # body_pose   : [1, 1, 1]
    # backpack    : [1, 4]
    # handbag     : [1, 4]
    #ub_length   : [1, 1]
    #lb_length   : [1, 1]
    #    staff       : [1, 2, 2]
    # holding_object: [1, 4]
