# DATA_FOLDER : /u01/Intern/chinhdv/DATA/milk/all_crop_data_origin
# train_csv : /u01/Intern/chinhdv/code/M_classification_torch/config/a/76classes_train_1103.csv
# val_csv: /u01/Intern/chinhdv/code/M_classification_torch/config/a/76classes_val_1103.csv
# TRAIN_FOLDER : /u01/DATA/HUMAN_ATTRIBUTE/PA_100K/data
TRAIN_FOLDER : /u01/Intern/chinhdv/github/auto_upload_cvat/hmat

train_csv : [
    # /u01/Intern/chinhdv/code/multi-task-classification/human_attribute_project/trainPA100K.csv,
    # /u01/Intern/chinhdv/code/multi-task-classification/human_attribute_project/0712_hmat.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_141_171_task_0000.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_141_171_task_0001.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_141_171_task_0002.csv,
    # /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_141_171_task_0003.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_141_171_task_0004.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_141_171_task_0005.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_141_171_task_0006.csv,
    # /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_141_171_task_0007.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_141_171_task_0008.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_141_171_task_0009.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_141_171_task_0010.csv,
    # /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_141_171_task_0011.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_20_140_task_0000.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_20_140_task_0001.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_20_140_task_0002.csv,
    # /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_20_140_task_0003.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_20_140_task_0004.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_20_140_task_0005.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_20_140_task_0006.csv,
    # /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_20_140_task_0007.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_20_140_task_0008.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_20_140_task_0009.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_20_140_task_0010.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_20_140_task_0011.csv,
    # /u01/Intern/chinhdv/code/multi-task-classification/human_attribute_project/VCR_HMAT_train.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_vin3s/vin3s_1.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_vin3s/vin3s_2.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_vin3s/vin3s_20_140_task_0012.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_vin3s/vin3s_20_140_task_0013.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_vin3s/vin3s_20_140_task_0014.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_vin3s/vin3s_20_140_task_0015.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_vin3s/vin3s_20_140_task_0016.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_vin3s/vin3s_20_140_task_0017.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_vin3s/vin3s_20_140_task_0018.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_vin3s/vin3s_20_140_task_0019.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_vin3s/vin3s_20_140_task_0020.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_vin3s/vin3s_20_140_task_0021.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_vin3s/vin3s_20_140_task_0022.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_vin3s/vin3s_20_140_task_0023.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_vin3s/vin3s_20_140_task_0024.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_vin3s/vin3s_entry_task_0000.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_vin3s/vin3s_entry_task_0001.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_vin3s/vin3s_entry_task_0002.csv,
    # /u01/Intern/chinhdv/code/multi-task-classification/human_attribute_project/vin3s_1_non_body_pose.csv
]
# val_csv : [
#     # /u01/Intern/chinhdv/code/multi-task-classification/human_attribute_project/trainPA100K.csv,
#     /u01/Intern/chinhdv/code/multi-task-classification/human_attribute_project/0812_hmat_test.csv
# ]
test_csv : [
#     # /u01/Intern/chinhdv/code/multi-task-classification/human_attribute_project/valPA100K.csv
#     /u01/Intern/chinhdv/code/multi-task-classification/human_attribute_project/human_attribute_test.csv
    
     /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_141_171_task_0003.csv,
     /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_141_171_task_0007.csv,
     /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_141_171_task_0011.csv,
     /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_20_140_task_0003.csv,
     /u01/Intern/chinhdv/github/auto_upload_cvat/dump_xml_vin3s_1502/vin3s_20_140_task_0007.csv,
    # /u01/Intern/chinhdv/code/multi-task-classification/human_attribute_project/VCR_HMAT_test.csv
    ]

classes:
  age         : [0-18, 18-55, 55+] 
  gender      : [female, male]
#   shape       : [thin,fat,kid]
  # hair        : [short_hair, long_hair]
  # hat         : ["no", "yes"]
  # glasses     : ["no", "yes"]
  # face_mask   : ["no", "yes"]
  # body_pose   : [front_pose, side_pose, turn_back_pose]
  # visible     : [fullbody, upperbody]
  # backpack    : ["no", "yes"]
  # handbag     : ["no", "yes"]
  ub_length   : [short, long]
  lb_length   : [short, long]
  staff       : ["no", SalesAssistant, TechnicalStaff]
  # action      : ['sitting','standing']
  # holding_object: ["no", "yes"]
#   crowd       : ["yes","no"]


# age, gender, shape, hair, hat, glasse


format_index: True

# task_weights : [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
task_weights : [1,1,1,1,1]
# task_weights : 1
class_weights:
    age: [2,1,2]
    gender: [1,1]
    # hair: [1,2]
    # hat         : [1, 1]
    # face_mask   : [1, 2]
    # glasses     : [1, 1]
    # visible     : [1,1]
    # body_pose   : [1, 1, 1]
    # backpack    : [1, 4]
    # handbag     : [1, 4]
    ub_length   : [1, 1]
    lb_length   : [1, 1]
    staff       : [1, 2, 2]
    # holding_object: [1, 4]
